#!/bin/bash
#  _ __  _ __   __ _ ___  ___ __ _ _ __
# | '_ \| '_ \ / _` / __|/ __/ _` | '_ \
# | |_) | | | | (_| \__ \ (_| (_| | | | |
# | .__/|_| |_|\__, |___/\___\__,_|_| |_|
# |_|          |___/
#
# Scan a document to create an image
# Usage: pngscan [filename]
set -e

export FILENAME=$1
if [[ $FILENAME == "" ]]; then
  export FILENAME="scan"
fi

# Get device - Currently set to look for epson2 compatible scanner on usb.
# Can also grep on "airscan" for wireless functionality, but response is
# not consistent.
DEVICE=$(scanimage -L | grep "epson2" | cut -d'`' -f2 | cut -d"'" -f1)

echo "Device is $DEVICE"

# Use scanimage to create the png file(s)
scanimage --device-name=$DEVICE --format=png --batch=$FILENAME.png \
  --batch-count=1 --batch-prompt --mode Color --resolution 300 -x 210

# Preview in ristretto
ristretto $FILENAME.png &
